language: go
script:
- env
env:
  global:
    secure: Xz7kdC9dmZJAoKRinw2z/IaM95YxbeL16IQs9zdhC3sKZByTlyNUuoRTAGPwKVCWlmzw7bqVVzxw6byh/wXxvWTHypH1OSFjJzP/Tr6ejEWp/PNk5aLIZ4QWafyAeR61rTyDudgi8BZoRlntALjrS8glouG+6D7KmwMltNm8rqOeRiWHFwqvtDZfxQGEOhMaRLIlgkb9tMEl2kT7RdBsQ7dppA0Hor8qoxlKiSnZVcg6B/3HLAnjZNanz/bHMAzj86jsQ5B/RCcyUAdAhgi6ZxIyuvyyFCXXM+RRbwH+xVSouDrb07nTD6IYv4xUeBYGxwuTdk+/H0Vo75pEVpmsi1+cjFE/VK6q6JTXx2Qox+pnPO0iDHe6dreAqfyMZ4PjSTixl6LQ0SJXl0vKwDwIWQeV+xcwGjz1TIRp8lfz6AKNeDO3poG7Emawb+rwDdTKxR5RqMlMXdfJy/Ir8ViBD9AV7Xiyn+bQKX2aLW8MyQjMFMwAfvWw0Pfl5IEx/2F4Qej2oqGbr7Zv0DDmIcSiW9EdB1GvZyY4N1Kozq2ayimtGpviZZEONWcqx3i/WFEUuzY3QgF7m0WwtdPZv4X7fHjzanm0WQmPFQXd9ZR1MhFi5nuQFhaqBNie4Sx8KTSx/Os18uxY1gLapbKL/gDoc9BHyj7uvW/Xruy+AXMyv98=
